### ISSUE TITLE
No module named 'modelsnet'

### ISSUE THREAD

**Issue by amiltonwong** [diegovalsesia/HyCoRe#2]
Hi, @diegovalsesia ,

Thanks for releasing the package. When I run the command `python main_dgcnn_hycore.py --epoch=250 --learning_rate 0.1 --msg=Offv_dgcnn_hycore_var --workers=8`, I got the following error:

```
(hycore) root@fa0e99c9a2ce:/data/code13/HyCoRe/classification_ScanObject#  python main_dgcnn_hycore.py --epoch=250 --learning_rate 0.1 --msg=Offv_dgcnn_hycore_var --workers=8
Traceback (most recent call last):
  File "main_dgcnn_hycore.py", line 21, in <module>
    import models as models
  File "/data/code13/HyCoRe/classification_ScanObject/models/__init__.py", line 3, in <module>
    from .pointmlp import pointMLP, pointMLPElite, Hype_pointMLP
  File "/data/code13/HyCoRe/classification_ScanObject/models/pointmlp.py", line 7, in <module>
    from modelsnet.ops.manifold_layers import GeodesicLayer, MobiusLayer, LogZero, ExpZero, GyroplaneConvLayer
ModuleNotFoundError: No module named 'modelsnet'
(hycore) root@fa0e99c9a2ce:/data/code13/HyCoRe/classification_ScanObject#
```

Any hints to fix this issue?

Thanks~

**Comment by diegovalsesia** [comment]
It was a leftover typo from a change in the directory name. I fixed it now.
